#ifndef DEVICE_TAGS_H
#define DEVICE_TAGS_H

#define DEVICE_TYPE 0x00
#define DEVICE_ROLE 0x11
#define DEVICE_MAC_ADDRESS 0x06
#define NUMBER_OF_CONTROLEES 0x05
#define DST_MAC_ADDRESS 0x07
#define RESULT_REPORT_CONFIG 0x2E
#define VENDOR_ID 0x27
#define STATIC_STS_IV 0x28
#define AOA_RESULT_REQ 0x0D
#define UWB_INITIATION_TIME 0x2B
#define RANGING_ROUND_USAGE 0x01
#define CHANNEL_NUMBER 0x04
#define PREAMBLE_CODE_INDEX 0x14
#define RFRAME_CONFIG 0x12
#define SFD_ID 0x15
#define SLOT_DURATION 0x08
#define RANGING_INTERVAL 0x09
#define SLOTS_PER_RR 0x1B
#define MULTI_NODE_MODE 0x03
#define HOPPING_MODE 0x2C
#define RSSI_REPORTING 0x36
#define ENABLE_DIAGNOSTICS 0xE8
#define DIAGS_FRAME_REPORTS_FIELDS 0xE9

#endif // DEVICE_TAGS_H
